version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: '06:00'
      day: "monday"
    cooldown:
      default-days: 7
    reviewers:
      - "SamJUK"
    assignees:
      - "SamJUK"
